CREATE TABLE IF NOT EXISTS stazioni (
    id VARCHAR(20) PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    nome_breve VARCHAR(255),
    lat DECIMAL(10, 6),
    lon DECIMAL(10, 6),
    regione INT,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS treni_cache (
    chiave VARCHAR(100) PRIMARY KEY,
    data JSON,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
